In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [12]:
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
54   60  Female   99.0    Mild     Mumbai
61   81  Female   98.0  Strong     Mumbai
83   17  Female  104.0    Mild    Kolkata
80   14  Female   99.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
69   73  Female  103.0    Mild      Delhi
98    5  Female   98.0  Strong     Mumbai
8    19  Female  100.0  Strong  Bangalore
85   16  Female  103.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore

[80 rows x 5 columns]

In [15]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [19]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [23]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city.shape

(80, 4)

In [27]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values
x_train_age.shape

(80, 1)

In [28]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed.shape

(80, 7)

from sklearn.compose import ColumnTransformer

In [29]:
from sklearn.compose import ColumnTransformer

In [32]:
trns=ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),
                                   ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                   ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
                                   ],remainder='passthrough')

In [34]:
trns.fit_transform(x_train).shape

(80, 7)

In [36]:
trns.transform(x_test).shape

(20, 7)