In [1]:

import numpy as np
import pandas as pd

In [3]:

date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [10]:
date['date']=pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date['date_year']=date['date'].dt.year

In [12]:
date['date_month_no']=date['date'].dt.month

In [14]:
date['date_month_name']=date['date'].dt.month_name()

In [17]:
date['date_day'] = date['date'].dt.day

In [27]:
date['date_dow'] = date['date'].dt.dayofweek
date['date_dow_name'] = date['date'].dt.day_name()
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id','city_id','orders'])

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1
...,...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,October,8,0,Monday,0
996,2018-12-06,2018,12,December,6,3,Thursday,0
997,2019-05-07,2019,5,May,7,1,Tuesday,0
998,2019-03-03,2019,3,March,3,6,Sunday,1
999,2019-10-15,2019,10,October,15,1,Tuesday,0

In [30]:
date['quarter'] = date['date'].dt.quarter
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [31]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 4, 29, 23, 31, 37, 429937)

In [33]:
(today-date['date']).dt.days

0      2332
1      2814
2      2745
3      2447
4      2670
       ...
995    2760
996    2701
997    2549
998    2614
999    2388
Name: date, Length: 1000, dtype: int64

In [39]:
((today.year - date['date'].dt.year) * 12 +
 (today.month - date['date'].dt.month))

0      76
1      92
2      90
3      80
4      87
       ..
995    90
996    88
997    83
998    85
999    78
Name: date, Length: 1000, dtype: int32

In [40]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [41]:

# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [42]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [43]:

time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [44]:
time['time'] = time['date'].dt.time
today - time['date']

0     4518 days 22:41:37.429937
1     4382 days 23:51:37.429937
2     4868 days 23:10:37.429937
3     4170 days 23:00:37.429937
4     4568 days 00:20:37.429937
                 ...
995   5157 days 22:41:37.429937
996   4479 days 00:17:37.429937
997   4943 days 23:54:37.429937
998   5059 days 23:57:37.429937
999   4332 days 00:06:37.429937
Name: date, Length: 1000, dtype: timedelta64[ns]

In [45]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.904369e+08
1      3.786907e+08
2      4.206786e+08
3      3.603708e+08
4      3.946764e+08
           ...
995    4.456465e+08
996    3.869867e+08
997    4.271613e+08
998    4.371839e+08
999    3.742852e+08
Name: date, Length: 1000, dtype: float64

In [46]:

# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.507282e+06
1      6.311512e+06
2      7.011311e+06
3      6.006181e+06
4      6.577941e+06
           ...
995    7.427442e+06
996    6.449778e+06
997    7.119355e+06
998    7.286398e+06
999    6.238087e+06
Name: date, Length: 1000, dtype: float64

In [47]:

# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108454.693731
1      105191.860397
2      116855.177064
3      100103.010397
4      109632.343731
           ...
995    123790.693731
996    107496.293731
997    118655.910397
998    121439.960397
999    103968.110397
Name: date, Length: 1000, dtype: float64