## data selection

In [1]:
import pandas as pd

In [3]:
df= pd.read_csv("data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [5]:
df["Date"]
df[["Date","Pulse"]]

            Date  Pulse
0   '2020/12/01'    110
1   '2020/12/02'    117
2   '2020/12/03'    103
3   '2020/12/04'    109
4   '2020/12/05'    117
5   '2020/12/06'    102
6   '2020/12/07'    110
7   '2020/12/08'    104
8   '2020/12/09'    109
9   '2020/12/10'     98
10  '2020/12/11'    103
11  '2020/12/12'    100
12  '2020/12/12'    100
13  '2020/12/13'    106
14  '2020/12/14'    104
15  '2020/12/15'     98
16  '2020/12/16'     98
17  '2020/12/17'    100
18  '2020/12/18'     90
19  '2020/12/19'    103
20  '2020/12/20'     97
21  '2020/12/21'    108
22           NaN    100
23  '2020/12/23'    130
24  '2020/12/24'    105
25  '2020/12/25'    102
26      20201226    100
27  '2020/12/27'     92
28  '2020/12/28'    103
29  '2020/12/29'    100
30  '2020/12/30'    102
31  '2020/12/31'     92

In [8]:
df.iloc[0]

Duration              60
Date        '2020/12/01'
Pulse                110
Maxpulse             130
Calories           409.1
Name: 0, dtype: object

In [9]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [12]:
df2=pd.read_csv("copy.csv")
df2.isna()
df2.dropna()

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'  110.0       130     409.1
2         60  '2020/12/03'  103.0       135     340.0
5         60  '2020/12/06'  102.0       127     300.0
7        450  '2020/12/08'  104.0       134     253.3
8         30  '2020/12/09'  109.0       133     195.1
9         60  '2020/12/10'   98.0       124     269.0
10        60  '2020/12/11'  103.0       147     329.3
11        60  '2020/12/12'  100.0       120     250.7
12        60  '2020/12/12'  100.0       120     250.7
14        60  '2020/12/14'  104.0       132     379.3
16        60  '2020/12/16'   98.0       120     215.2
17        60  '2020/12/17'  100.0       120     300.0
19        60  '2020/12/19'  103.0       123     323.0
20        45  '2020/12/20'   97.0       125     243.0
21        60  '2020/12/21'  108.0       131     364.2
23        60  '2020/12/23'  130.0       101     300.0
24        45  '2020/12/24'  105.0       132     246.0
25        60  '2020/12/25'  102.0       126     334.5
26        60      20201226  100.0       120     250.0
27        60  '2020/12/27'   92.0       118     241.0
29        60  '2020/12/29'  100.0       132     280.0
30        60  '2020/12/30'  102.0       129     380.3
31        60  '2020/12/31'   92.0       115     243.0

In [13]:
df2.fillna(0)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'  110.0       130     409.1
1         60             0  117.0       145     479.0
2         60  '2020/12/03'  103.0       135     340.0
3         45  '2020/12/04'    0.0       175     282.4
4         45             0  117.0       148     406.0
5         60  '2020/12/06'  102.0       127     300.0
6         60  '2020/12/07'    0.0       136     374.0
7        450  '2020/12/08'  104.0       134     253.3
8         30  '2020/12/09'  109.0       133     195.1
9         60  '2020/12/10'   98.0       124     269.0
10        60  '2020/12/11'  103.0       147     329.3
11        60  '2020/12/12'  100.0       120     250.7
12        60  '2020/12/12'  100.0       120     250.7
13        60             0  106.0       128     345.3
14        60  '2020/12/14'  104.0       132     379.3
15        60  '2020/12/15'    0.0       123     275.0
16        60  '2020/12/16'   98.0       120     215.2
17        60  '2020/12/17'  100.0       120     300.0
18        45  '2020/12/18'    0.0       112       0.0
19        60  '2020/12/19'  103.0       123     323.0
20        45  '2020/12/20'   97.0       125     243.0
21        60  '2020/12/21'  108.0       131     364.2
22        45             0  100.0       119     282.0
23        60  '2020/12/23'  130.0       101     300.0
24        45  '2020/12/24'  105.0       132     246.0
25        60  '2020/12/25'  102.0       126     334.5
26        60      20201226  100.0       120     250.0
27        60  '2020/12/27'   92.0       118     241.0
28        60  '2020/12/28'  103.0       132       0.0
29        60  '2020/12/29'  100.0       132     280.0
30        60  '2020/12/30'  102.0       129     380.3
31        60  '2020/12/31'   92.0       115     243.0

In [16]:
df.rename(columns={"Date":"DateTime"},inplace=True)
df.head()

   Duration      DateTime  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [20]:

df["Pulse"]=df["Pulse"].astype("float")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   DateTime  31 non-null     object
 2   Pulse     32 non-null     float64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.4+ KB

In [26]:
df["Pulse"][0]
len(df)
df["zeros"]=[0 for i in range(len(df))]
df.head()

   Duration      DateTime  Pulse  Maxpulse  Calories  zeros
0        60  '2020/12/01'  110.0       130     409.1      0
1        60  '2020/12/02'  117.0       145     479.0      0
2        60  '2020/12/03'  103.0       135     340.0      0
3        45  '2020/12/04'  109.0       175     282.4      0
4        45  '2020/12/05'  117.0       148     406.0      0

In [27]:
def fun(a):
    return a+2;
df["zero +1 "]=df["zeros"].apply(fun)
df.head()

   Duration      DateTime  Pulse  Maxpulse  Calories  zeros  zero +1
0        60  '2020/12/01'  110.0       130     409.1      0         2
1        60  '2020/12/02'  117.0       145     479.0      0         2
2        60  '2020/12/03'  103.0       135     340.0      0         2
3        45  '2020/12/04'  109.0       175     282.4      0         2
4        45  '2020/12/05'  117.0       148     406.0      0         2

In [28]:
df.to_csv("new.csv",index=False)

In [32]:
d1=pd.DataFrame({"Name":["Ahmad","Ali","Hassan","Abu Bakr"],"Marks":[95,80,50,40]})
d1
d2=pd.DataFrame({"Name":["Ahmad","Ali","Arslan","Hamza"],"age":[20,21,19,22]})
pd.concat([d1,d2])
pd.merge(d1,d2,on="Name")

    Name  Marks  age
0  Ahmad     95   20
1    Ali     80   21